In [1]:
import json
import pandas as pd
import numpy as np
import math
from scipy import optimize
from datetime import datetime
import prettytable as pt
from matplotlib import pyplot as plt
import os
import prettytable as pt
import warnings
warnings.filterwarnings("ignore")



###################################################################################################
                                                                                                  #
from rhoova.Client import *                                                                       #   
#Register and get api key from https://app.rhoova.com/ for ClientConfig("api key", "api secret")  #
config = ClientConfig("", "")                                                                     #
api = Api(config)                                                                                 # 
                                                                                                  #
###################################################################################################

In [3]:

data = {
    "capital": 10000,
    "interestRate": 0.01,
    "cgf": 0.15,
    "tax": 0.05,
    "frequency": "Monthly",
    "valuationDate": "2016-12-20",
    "maturityDate": "2017-12-20",
    "depositDefinition": {
        "dayCounter": "ActualActual",
        "calendar": "TARGET",
        "businessDayConvention": "Following",
        "maturityDateConvention": "Following",
        "dateGeneration": "Backward",
        "endOfMonth": True
    }
}

try:
    bondresult = api.createTask(CalculationType.LOAN, data,True)
    result=json.loads(bondresult["result"])
except RhoovaError as e:
    e.printPretty()

In [6]:
cashflows=pd.DataFrame(result)

In [7]:
cashflows

,day,termToMatByYear,termToMatByDay,cashflow,interest,cgf,tax,principal,endingBalance
0,2016-12-20,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,10000.000000
1,2017-01-20,0.084842,31,899.754333,101.810016,15.271502,5.090501,777.582314,9222.417686
2,2017-02-20,0.169773,62,899.754333,93.992860,14.098929,4.699643,786.962901,8435.454785
3,2017-03-20,0.246486,90,899.754333,77.652406,11.647861,3.882620,806.571446,7628.883339
4,2017-04-20,0.331417,121,899.754333,77.751907,11.662786,3.887595,806.452045,6822.431294
5,2017-05-22,0.419088,153,899.754333,71.775716,10.766357,3.588786,813.623474,6008.807820
6,2017-06-20,0.498540,182,899.754333,57.289455,8.593418,2.864473,831.006986,5177.800834
7,2017-07-20,0.580732,212,899.754333,51.068721,7.660308,2.553436,838.471868,4339.328966
8,2017-08-21,0.668403,244,899.754333,45.652118,6.847818,2.282606,844.971791,3494.357175
9,2017-09-20,0.750595,274,899.754333,34.464893,5.169734,1.723245,858.396462,2635.960714
10,2017-10-20,0.832787,304,899.754333,25.998517,3.899777,1.299926,868.556113,1767.404601
11,2017-11-20,0.917718,335,899.754333,18.013000,2.701950,0.900650,878.138732,889.265868
12,2017-12-20,0.999910,365,899.754333,8.807387,1.321108,0.440369,889.185469,0.000000